### ISSUE TITLE
[Windows 7] Titanfall.exe stoped working

### ISSUE THREAD

**Issue by hoolygunn** [p0358/black_market_edition#19] opened 2024-10-23 09:25 UTC
[bme.log](https://github.com/user-attachments/files/17488382/bme.log)

**Comment by p0358** [comment] 2024-10-23 11:33
Hmm, this does seem to be a crash on shutdown though, right?

**Comment by p0358** [comment] 2024-10-23 11:47
Found out the cause, will be fixed in next release

**Closed as completed** 2024-10-23 11:47 UTC
